services:
  db:
    image: mongo:4.4.13
    container_name: "mongo-db"
    ports:
      - "27017:27017"
    restart: unless-stopped
  app:
    build: .
    image: crud-spring-app:1.0
    container_name: "spring-app"
    ports:
      - "8080:8080"
    depends_on:
      - db