services:
  db:
    image: mongo:latest
    container_name: "mongo-db"
    ports:
      - "27017:27017"
  app:
    build: .
    image: crud-spring-app:1.0
    container_name: "spring-app"
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=db
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=crud
      - spring.data.mongodb.auto-index-creation=true
      - server.contextPath=/api/v1
    depends_on:
      - db